"""Add domain column to notes

Revision ID: 201356773e75
Revises: 6d67ab8c8e21
Create Date: 2026-01-23 21:23:41.935295

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "201356773e75"
down_revision = "6d67ab8c8e21"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("notes", sa.Column("domain", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("notes", "domain")
    # ### end Alembic commands ###
