"""add_processed_field

Revision ID: 6d67ab8c8e21
Revises: aaf000e4972c
Create Date: 2026-01-12 21:39:35.625671

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6d67ab8c8e21"
down_revision = "aaf000e4972c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("notes", sa.Column("processed", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("notes", "processed")
    # ### end Alembic commands ###
